POST http://localhost:4000/event
Content-Type: application/json

 {  
   "eventTitle":"Super anniversaire",
   "eventTicketingTitle":"https://www.youtube.com/",
   "eventDate":"Du 6 juillet au 21 juillet",
   "eventImage":"image de l'event",
   "eventDescription":"ceci est la description",
   "eventAddress":"9 rue de la charretière, Saint Genis Laval",
   "eventType":"Soirée",
   "isFavorite": false
 }